#!/bin/bash

APIAI_CLIENT_ACCESS_TOKEN=[your APIAI_CLIENT_ACCESS_TOKEN] \
LINE_CHANNEL_ACCESS_TOKEN=[your LINE_CHANNEL_ACCESS_TOKEN] \
LINE_CHANNEL_SECRET=[your LINE_CHANNEL_SECRET] \
node index.js

exit 0
